### PR TITLE
EnsureOakIndex updates

### PR DESCRIPTION
**Pull request by davidjgonzalez**
- Class/Method renaming
- Servlet to MBean
- Removed extra Solr classes

WDYT about making the HTTP interactions with this via the Felix MBean tooling. This is the tooling we use for all other Felix-based interactions. 

2016-01-03 at 8 03 pm

### CODE REVIEW

**Comment by joerghoh** [comment]
I am not a real big fan of the JMX console (unless you have an application monitoring tool, which is capable to use JMX), but rather prefer a simple webconsole page (gives a little more flexibility when it comes to formatting the output). But I am fine with the JMX approach here.

Besides that: I think, that the removal of the solr things should go into a different pull request :-)

**Comment by davidjgonzalez** [comment]
If there is a good reason to not use the mbean I'm all for it; it just provides all the facilities to do what it seems you're trying to do. 

Wdyt about a simple server end point that responds w just a status code (no html) that then calls the ensure method exposed by the mbean. Having the build call the mbean uri does feel less clean (since it's an ugly url) 

Tbh I'm not sure where at solr stuff came from. I removed it since it was breaking the build. It'd probably be best to pull only the files needed into a new branch off master.

**Comment by joerghoh** [comment]
Regarding the servlet: If we make it available using the webconsole, we should also provide a proper "GET" method, which displays all available indexes (like my webconsole already does), plus a way run the ensureOakIndex functionality for each available configuration.

But instead of insisting on a perfect solution I am rather interested in bringing the functionality to explicitly start the ensureIndex process (and therefor the Oak indexing) as soon as possible into an ACS Commons release.

So I will merge your request, do a final check and then start the pull request for master.

**Comment by davidjgonzalez** [comment]
@joerghoh IMO the purpose of the HTTP Servlet is to allow clean(er) interaction by automated build systems; using a HTTP Response code is a great idea to indicate success (its their raison d'etre after all)

In the the case of HTTP GET's, this servlet serves no real purpose and we should let programmatic callers know this. If we return a 200 on a GET its much harder to detect.

Any Human interaction should go through the MBean - since this has all the facilities for this and we dont have to build out custom UIs. I dont see the benefit re-inventing the wheel that the felix jmx already created.

I'm fine registering this servlet to a different path, but we'd need to make sure its locked down very well (the felix webconsole space has a the "perk" of being restricted to highly privileged web console users)

**Comment by joerghoh** [comment]
Agree, but have you already tried the URL system/console/ensure-oak-index? The webconsole does not check, if the Servlet does not support GETs, and adds this servlet as entry to the "Main" menu. Of course you get the error message then, but it's confusing. I would be glad to remove it from the menu, but I am not aware of a way to achieve this.

**Comment by davidjgonzalez** [comment]
@joerghoh Ah - I didn't see/notice it in Main. I figured with only the label, it wouldn't register for the menu.

Also - is the Felix console management access controls sufficient? For example, on my current project we have our build automation user that wouldnt have access to the Web Console (as is currently configured).

**Comment by joerghoh** [comment]
Felix Access Control is sufficient, on my current project we will use the service interface anyways instead of any HTTP call.

**Comment by davidjgonzalez** [comment]
@joerghoh is it generally sufficient? Im not sure it is, case in point my current project where the build user doesn't have access.

I wonder if we should make it a Sling Servlet, and do some sort of configurable authorization management in that.

**Comment by joerghoh** [comment]
I chatted offline with @davidjgonzalez and we come up with the idea, that we migrate EnsureOakIndexServlet to a SlingServlet, and we will provide these properties with empty values:
- sling.servlet.path
- sling.servlet.resourceTypes
  In that case the servlet is not usable at all. If you want to use it, you either have to bind it to a path (and then it's up to the user to secure this path) or bind it to a resourcetype and then create a node using this resourcetype and secure this node using ACLs.

Using this approach the servlet isn't registered by default which is good from a security point of view. When desired, we can still improve it.
WDYT?

**Pull request merged**
